server:
  port: 8080

spring:
  application:
    name: finalproject
  profiles:
    active: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  ai:
    custom:
      system-prompt: ${SPRING_AI_SYSTEM_PROMPT}
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_MODEL}
          temperature: ${SPRING_AI_OPENAI_TEMPERATURE}

  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ict.finalproject
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org.mybatis: TRACE

file:
  pdf-dir: ${FILE_PDF_DIR}

api:
  gpt:
    key: ${API_GPT_KEY}
    model: ${API_GPT_MODEL}
  naver:
    client-id: ${API_NAVER_CLIENT_ID}
    client-secret: ${API_NAVER_CLIENT_SECRET}

mail:
  smtp:
    host: smtp.naver.com
    port: 587
    auth: true
    starttls:
      enable: true
    username: ${MAIL_SMTP_USERNAME}
    password: ${MAIL_SMTP_PASSWORD}
    sender:
      name: AI-InterView관리자

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 900000
  refresh-token-validity: 86400000
